<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use App\Models\role;
use App\Models\master_satker;
use App\Models\master_wilayah;
use App\Models\user;
use App\Models\master_komoditas;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        // Hapus semua data dari tabel
        role::truncate();
        master_satker::truncate();
        master_wilayah::truncate();
        master_komoditas::truncate();
        user::truncate();

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        role::insert([
            ['id' => 1, 'nama_role' => 'Admin Provinsi'],
            ['id' => 2, 'nama_role' => 'Admin Kabkot'],
        ]);

        master_satker::insert([
            ['kode_satker' => 3500, 'nama_satker' => 'PROV JAWA TIMUR'],
            ['kode_satker' => 3504, 'nama_satker' => 'KAB TULUNGAGUNG'],
            ['kode_satker' => 3509, 'nama_satker' => 'JEMBER'],
            ['kode_satker' => 3510, 'nama_satker' => 'BANYUWANGI'],
            ['kode_satker' => 3522, 'nama_satker' => 'KAB BOJONEGORO'],
            ['kode_satker' => 3525, 'nama_satker' => 'KAB GRESIK'],
            ['kode_satker' => 3529, 'nama_satker' => 'SUMENEP'],
            ['kode_satker' => 3571, 'nama_satker' => 'KOTA KEDIRI'],
            ['kode_satker' => 3573, 'nama_satker' => 'KOTA MALANG'],
            ['kode_satker' => 3574, 'nama_satker' => 'KOTA PROBOLINGGO'],
            ['kode_satker' => 3577, 'nama_satker' => 'KOTA MADIUN'],
            ['kode_satker' => 3578, 'nama_satker' => 'KOTA SURABAYA'],
        ]);

        master_wilayah::insert([
            ['kode_wil' => 3500, 'nama_wil' => 'PROV JAWA TIMUR'],
            ['kode_wil' => 3504, 'nama_wil' => 'KAB TULUNGAGUNG'],
            ['kode_wil' => 3509, 'nama_wil' => 'JEMBER'],
            ['kode_wil' => 3510, 'nama_wil' => 'BANYUWANGI'],
            ['kode_wil' => 3522, 'nama_wil' => 'KAB BOJONEGORO'],
            ['kode_wil' => 3525, 'nama_wil' => 'KAB GRESIK'],
            ['kode_wil' => 3529, 'nama_wil' => 'SUMENEP'],
            ['kode_wil' => 3571, 'nama_wil' => 'KOTA KEDIRI'],
            ['kode_wil' => 3573, 'nama_wil' => 'KOTA MALANG'],
            ['kode_wil' => 3574, 'nama_wil' => 'KOTA PROBOLINGGO'],
            ['kode_wil' => 3577, 'nama_wil' => 'KOTA MADIUN'],
            ['kode_wil' => 3578, 'nama_wil' => 'KOTA SURABAYA'],
        ]);

        // Seed users
        user::insert([
            [
                'id' => (string) Str::uuid(),
                'id_satker' => 3500,
                'id_role' => 1,
                'nama' => 'Admin Prov',
                'email' => 'adminprov@example.com',
                'password' => Hash::make('1234'),
            ],
            [
                'id' => (string) Str::uuid(),
                'id_satker' => 3578,
                'id_role' => 2,
                'nama' => 'Admin Kabkot',
                'email' => 'adminkabkot@example.com',
                'password' => Hash::make('1234'),
            ],
        ]);

        master_komoditas::insert([
            ['kode_kom' => '0', 'nama_kom' => 'UMUM', 'flag' => 0, 'flag_2' => null],
                ['kode_kom' => '01', 'nama_kom' => 'MAKANAN, MINUMAN DAN TEMBAKAU', 'flag' => 1, 'flag_2' => 0],
                ['kode_kom' => '011', 'nama_kom' => 'MAKANAN', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0111001', 'nama_kom' => 'BERAS', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0111002', 'nama_kom' => 'BERAS JAGUNG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0111008', 'nama_kom' => 'TEPUNG TERIGU', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0111013', 'nama_kom' => 'BISKUIT', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0111017', 'nama_kom' => 'MAKANAN RINGAN/SNACK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0111018', 'nama_kom' => 'ROTI MANIS', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0111019', 'nama_kom' => 'ROTI TAWAR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0111020', 'nama_kom' => 'KERUPUK (MENTAH)', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0111021', 'nama_kom' => 'WAFER', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0111024', 'nama_kom' => 'KUE KERING', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0111025', 'nama_kom' => 'DONAT', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0111027', 'nama_kom' => 'KUE BOLU/TART', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0111032', 'nama_kom' => 'SEREAL/HAVERMOOT', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0111037', 'nama_kom' => 'BROWNIES', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0111047', 'nama_kom' => 'MIE KERING INSTANT', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0111048', 'nama_kom' => 'SOUN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0111050', 'nama_kom' => 'MIE KERING', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0112001', 'nama_kom' => 'AYAM HIDUP', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0112003', 'nama_kom' => 'DAGING AYAM RAS', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0112004', 'nama_kom' => 'DAGING BABI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0112005', 'nama_kom' => 'DAGING KAMBING', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0112008', 'nama_kom' => 'DAGING SAPI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0112021', 'nama_kom' => 'RAMPELA HATI AYAM', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0112024', 'nama_kom' => 'BAKSO (MENTAH)', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0112026', 'nama_kom' => 'SOSIS', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0112027', 'nama_kom' => 'NUGGET', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113001', 'nama_kom' => 'IKAN BANDENG/IKAN BOLU', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113004', 'nama_kom' => 'IKAN BAWAL', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113005', 'nama_kom' => 'IKAN BELANAK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113008', 'nama_kom' => 'IKAN BIJI NANGKA/IKAN KUNIRAN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113010', 'nama_kom' => 'IKAN CAKALANG/ IKAN SISIK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113014', 'nama_kom' => 'IKAN EKOR KUNING', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113017', 'nama_kom' => 'IKAN GURAME', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113019', 'nama_kom' => 'IKAN KAKAP MERAH', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113020', 'nama_kom' => 'IKAN KAKAP PUTIH', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113024', 'nama_kom' => 'IKAN KEMBUNG/IKAN GEMBUNG/ IKAN BANYAR/IKAN GEMBOLO/ IKAN ASO-ASO', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113025', 'nama_kom' => 'IKAN KERAPU/ IKAN GAROPA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113028', 'nama_kom' => 'IKAN LAMURU', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113029', 'nama_kom' => 'IKAN LAYANG/ IKAN BENGGOL', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113030', 'nama_kom' => 'IKAN LELE', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113035', 'nama_kom' => 'IKAN MUJAIR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113036', 'nama_kom' => 'IKAN NILA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113039', 'nama_kom' => 'IKAN PATIN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113043', 'nama_kom' => 'IKAN SELAR/ IKAN TUDE', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113050', 'nama_kom' => 'IKAN TENGGIRI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113051', 'nama_kom' => 'IKAN TERI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113053', 'nama_kom' => 'IKAN TONGKOL/ IKAN AMBU-AMBU', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113055', 'nama_kom' => 'IKAN TUNA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113060', 'nama_kom' => 'IKAN KERISI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113225', 'nama_kom' => 'IKAN ASIN BELAH', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113228', 'nama_kom' => 'IKAN DALAM KALENG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113236', 'nama_kom' => 'IKAN ASIN PEDA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113237', 'nama_kom' => 'PINDANG ASIN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113240', 'nama_kom' => 'IKAN ASIN TERI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113242', 'nama_kom' => 'IKAN PANGGANG/MANGUT', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113246', 'nama_kom' => 'IKAN ASAP', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113250', 'nama_kom' => 'BANDENG DIAWETKAN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113254', 'nama_kom' => 'TONGKOL DIAWETKAN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113255', 'nama_kom' => 'SALEM DIAWETKAN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113311', 'nama_kom' => 'CUMI-CUMI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113312', 'nama_kom' => 'KEPITING/RAJUNGAN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113313', 'nama_kom' => 'KERANG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0113314', 'nama_kom' => 'UDANG BASAH', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0114001', 'nama_kom' => 'SUSU SAPI MURNI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0114002', 'nama_kom' => 'SUSU CAIR KEMASAN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0114005', 'nama_kom' => 'SUSU BUBUK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0114006', 'nama_kom' => 'SUSU KENTAL MANIS', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0114007', 'nama_kom' => 'SUSU BUBUK UNTUK WANITA HAMIL', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0114008', 'nama_kom' => 'SUSU BUBUK UNTUK TULANG/MANULA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0114014', 'nama_kom' => 'KEJU', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0114015', 'nama_kom' => 'SUSU FERMENTASI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0114017', 'nama_kom' => 'TELUR AYAM KAMPUNG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0114018', 'nama_kom' => 'TELUR AYAM RAS', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0114020', 'nama_kom' => 'TELUR PUYUH', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0115001', 'nama_kom' => 'MARGARINE', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0115002', 'nama_kom' => 'MINYAK GORENG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0116001', 'nama_kom' => 'ALPUKAT', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0116004', 'nama_kom' => 'MANGGA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0116005', 'nama_kom' => 'NANAS', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0116006', 'nama_kom' => 'PEPAYA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0116007', 'nama_kom' => 'PISANG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0116008', 'nama_kom' => 'SALAK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0116009', 'nama_kom' => 'KELAPA MUDA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0116050', 'nama_kom' => 'JERUK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0116055', 'nama_kom' => 'APEL', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0116056', 'nama_kom' => 'PIR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0116063', 'nama_kom' => 'ANGGUR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0116064', 'nama_kom' => 'MELON', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0116065', 'nama_kom' => 'SEMANGKA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0116078', 'nama_kom' => 'KELAPA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0116084', 'nama_kom' => 'KACANG TANAH', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117001', 'nama_kom' => 'BAYAM', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117004', 'nama_kom' => 'DAUN KELOR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117007', 'nama_kom' => 'DAUN PAKU / PAKIS', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117009', 'nama_kom' => 'SELADA/DAUN SELADA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117010', 'nama_kom' => 'DAUN SINGKONG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117011', 'nama_kom' => 'KANGKUNG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117012', 'nama_kom' => 'KEMBANG KOL', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117013', 'nama_kom' => 'KOL PUTIH/KUBIS', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117015', 'nama_kom' => 'SAWI HIJAU', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117017', 'nama_kom' => 'DAUN KEMANGI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117018', 'nama_kom' => 'BROKOLI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117020', 'nama_kom' => 'SAWI PUTIH/PECAY/PITSAI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117088', 'nama_kom' => 'KETIMUN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117090', 'nama_kom' => 'LABU SIAM/JIPANG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117091', 'nama_kom' => 'CABAI HIJAU', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117092', 'nama_kom' => 'NANGKA MUDA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117094', 'nama_kom' => 'PEPAYA MUDA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117097', 'nama_kom' => 'JAGUNG MANIS', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117098', 'nama_kom' => 'OYONG/GAMBAS/BESTRU/EMES', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117099', 'nama_kom' => 'JAGUNG MUDA/PUTREN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117102', 'nama_kom' => 'TERONG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117103', 'nama_kom' => 'TOMAT', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117104', 'nama_kom' => 'CABAI MERAH', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117105', 'nama_kom' => 'CABAI RAWIT', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117124', 'nama_kom' => 'BUNCIS', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117125', 'nama_kom' => 'KACANG PANJANG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117128', 'nama_kom' => 'DAUN BAWANG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117129', 'nama_kom' => 'DAUN SELEDRI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117130', 'nama_kom' => 'JAMUR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117133', 'nama_kom' => 'TAUGE/KECAMBAH', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117134', 'nama_kom' => 'WORTEL', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117136', 'nama_kom' => 'BAWANG BOMBAY', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117137', 'nama_kom' => 'BAWANG MERAH', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117138', 'nama_kom' => 'BAWANG PUTIH', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117157', 'nama_kom' => 'KETELA POHON', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117160', 'nama_kom' => 'KENTANG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117163', 'nama_kom' => 'KACANG HIJAU', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117174', 'nama_kom' => 'TAHU MENTAH', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0117176', 'nama_kom' => 'TEMPE', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0118001', 'nama_kom' => 'GULA PASIR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0118003', 'nama_kom' => 'GULA MERAH', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0118008', 'nama_kom' => 'SELAI / JAM', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0118009', 'nama_kom' => 'MADU', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0118011', 'nama_kom' => 'COKLAT BATANG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0118012', 'nama_kom' => 'ICE CREAM', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0118014', 'nama_kom' => 'KEMBANG GULA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0119001', 'nama_kom' => 'KUE BASAH', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0119002', 'nama_kom' => 'TELUR ASIN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0119005', 'nama_kom' => 'NASI JAGUNG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0119039', 'nama_kom' => 'SUSU BUBUK UNTUK BALITA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0119040', 'nama_kom' => 'SUSU BUBUK UNTUK BAYI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0119041', 'nama_kom' => 'MAKANAN BAYI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0119044', 'nama_kom' => 'PENYEDAP MASAKAN/VETSIN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0119045', 'nama_kom' => 'BUMBU MASAK JADI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0119046', 'nama_kom' => 'GARAM', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0119047', 'nama_kom' => 'KECAP', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0119048', 'nama_kom' => 'SAMBAL JADI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0119049', 'nama_kom' => 'SAUS TOMAT', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0119050', 'nama_kom' => 'TERASI UDANG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0119051', 'nama_kom' => 'TEPUNG BUMBU', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0119052', 'nama_kom' => 'PETIS MADURA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0119053', 'nama_kom' => 'BUMBU/SAMBAL PECEL', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0119054', 'nama_kom' => 'SANTAN JADI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0119062', 'nama_kom' => 'SAUS TIRAM', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0119080', 'nama_kom' => 'KEMIRI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0119082', 'nama_kom' => 'LADA/MERICA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0119107', 'nama_kom' => 'BAHAN AGAR-AGAR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '012', 'nama_kom' => 'MINUMAN YANG TIDAK BERALKOHOL', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0121002', 'nama_kom' => 'JUS BUAH SIAP SAJI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0122001', 'nama_kom' => 'KOPI BUBUK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0123001', 'nama_kom' => 'TEH', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0125001', 'nama_kom' => 'AIR KEMASAN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0126001', 'nama_kom' => 'MINUMAN RINGAN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0129001', 'nama_kom' => 'MINUMAN KESEGARAN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '014', 'nama_kom' => 'ROKOK DAN TEMBAKAU', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0141001', 'nama_kom' => 'SIGARET KRETEK TANGAN (SKT)', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0141002', 'nama_kom' => 'SIGARET KRETEK MESIN (SKM)', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0141003', 'nama_kom' => 'SIGARET PUTIH MESIN (SPM)', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '02', 'nama_kom' => 'PAKAIAN DAN ALAS KAKI', 'flag' => 1, 'flag_2' => 0],
                ['kode_kom' => '021', 'nama_kom' => 'PAKAIAN', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0211003', 'nama_kom' => 'BAHAN KATUN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0211006', 'nama_kom' => 'KAIN BATIK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0211009', 'nama_kom' => 'BAHAN RENDA/BRUKAT', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212001', 'nama_kom' => 'BAJU KAOS BERKERAH PRIA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212002', 'nama_kom' => 'CELANA DALAM PRIA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212003', 'nama_kom' => 'CELANA PANJANG JEANS PRIA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212004', 'nama_kom' => 'CELANA PANJANG KATUN PRIA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212006', 'nama_kom' => 'CELANA PENDEK PRIA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212007', 'nama_kom' => 'JAKET PRIA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212008', 'nama_kom' => 'KAOS KAKI PRIA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212009', 'nama_kom' => 'KAOS KUTANG/SINGLET PRIA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212010', 'nama_kom' => 'BAJU KAOS TANPA KERAH/ T-SHIRT PRIA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212011', 'nama_kom' => 'KEMEJA PANJANG BATIK PRIA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212012', 'nama_kom' => 'KEMEJA PANJANG KATUN PRIA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212014', 'nama_kom' => 'KEMEJA PENDEK BATIK PRIA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212015', 'nama_kom' => 'KEMEJA PENDEK KATUN PRIA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212018', 'nama_kom' => 'BAJU MUSLIM PRIA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212020', 'nama_kom' => 'SARUNG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212021', 'nama_kom' => 'BAJU KAOS BERKERAH ANAK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212022', 'nama_kom' => 'CELANA PANJANG JEANS ANAK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212023', 'nama_kom' => 'CELANA PANJANG KATUN ANAK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212024', 'nama_kom' => 'CELANA PENDEK ANAK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212025', 'nama_kom' => 'KAOS KAKI ANAK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212026', 'nama_kom' => 'KAOS DALAM/SINGLET ANAK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212027', 'nama_kom' => 'BAJU KAOS TANPA KERAH / T-SHIRT ANAK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212028', 'nama_kom' => 'KEMEJA PENDEK ANAK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212029', 'nama_kom' => 'BAJU ANAK STELAN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212030', 'nama_kom' => 'JAS HUJAN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212031', 'nama_kom' => 'PAKAIAN OLAH RAGA PRIA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212059', 'nama_kom' => 'BAJU KAOS BERKERAH WANITA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212060', 'nama_kom' => 'BAJU MUSLIM WANITA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212061', 'nama_kom' => 'BAJU TIDUR WANITA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212062', 'nama_kom' => 'BAJU BATIK WANITA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212063', 'nama_kom' => 'BLUS WANITA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212064', 'nama_kom' => 'CELANA DALAM WANITA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212065', 'nama_kom' => 'CELANA PANJANG JEANS WANITA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212066', 'nama_kom' => 'CELANA PANJANG KATUN WANITA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212068', 'nama_kom' => 'DASTER', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212069', 'nama_kom' => 'GAUN/TERUSAN WANITA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212072', 'nama_kom' => 'KEMEJA PENDEK WANITA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212073', 'nama_kom' => 'KEMEJA PANJANG SERAT SINTETIS WANITA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212074', 'nama_kom' => 'KULOT WANITA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212075', 'nama_kom' => 'MUKENA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212076', 'nama_kom' => 'ROK LUAR MODEL BIASA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212083', 'nama_kom' => 'KEMEJA PANJANG KATUN WANITA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212085', 'nama_kom' => 'BH (BRA)', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212087', 'nama_kom' => 'GAUN ANAK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212089', 'nama_kom' => 'BAJU MUSLIM ANAK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212090', 'nama_kom' => 'KERUDUNG/JILBAB', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212091', 'nama_kom' => 'PAKAIAN OLAH RAGA WANITA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212102', 'nama_kom' => 'BAJU KAOS TANPA KERAH / T-SHIRT WANITA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212120', 'nama_kom' => 'CELANA DALAM ANAK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212121', 'nama_kom' => 'PAKAIAN BAYI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212125', 'nama_kom' => 'JAKET ANAK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212144', 'nama_kom' => 'SERAGAM SEKOLAH PRIA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212145', 'nama_kom' => 'SERAGAM SEKOLAH WANITA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0212147', 'nama_kom' => 'SERAGAM SEKOLAH ANAK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0213003', 'nama_kom' => 'TUTUP KEPALA/TOPI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0214001', 'nama_kom' => 'ONGKOS BINATU/LAUNDRY', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0214002', 'nama_kom' => 'ONGKOS JAHIT', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '022', 'nama_kom' => 'ALAS KAKI', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0221001', 'nama_kom' => 'SANDAL KARET PRIA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0221002', 'nama_kom' => 'SANDAL KULIT PRIA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0221003', 'nama_kom' => 'SEPATU PRIA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0221004', 'nama_kom' => 'SANDAL KARET WANITA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0221005', 'nama_kom' => 'SANDAL KULIT WANITA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0221006', 'nama_kom' => 'SEPATU WANITA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0221007', 'nama_kom' => 'SANDAL ANAK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0221008', 'nama_kom' => 'SEPATU ANAK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0221009', 'nama_kom' => 'SEPATU OLAH RAGA PRIA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0221010', 'nama_kom' => 'SEPATU OLAH RAGA WANITA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '03', 'nama_kom' => 'PERUMAHAN, AIR, LISTRIK, DAN BAHAN BAKAR RUMAH TANGGA', 'flag' => 1, 'flag_2' => 0],
                ['kode_kom' => '031', 'nama_kom' => 'SEWA DAN KONTRAK RUMAH', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0311001', 'nama_kom' => 'KONTRAK RUMAH', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0311002', 'nama_kom' => 'SEWA RUMAH', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '032', 'nama_kom' => 'PEMELIHARAAN, PERBAIKAN, DAN KEAMANAN TEMPAT TINGGAL/PERUMAHAN', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0321001', 'nama_kom' => 'ASBES', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0321002', 'nama_kom' => 'BATAKO', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0321003', 'nama_kom' => 'BATU BATA/BATU TELA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0321004', 'nama_kom' => 'BESI BETON', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0321005', 'nama_kom' => 'CAT KAYU', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0321006', 'nama_kom' => 'CAT TEMBOK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0321007', 'nama_kom' => 'CLOSET', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0321009', 'nama_kom' => 'DAUN PINTU', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0321010', 'nama_kom' => 'GENTENG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0321013', 'nama_kom' => 'KAYU BALOKAN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0321014', 'nama_kom' => 'KAYU LAPIS', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0321015', 'nama_kom' => 'KERAMIK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0321016', 'nama_kom' => 'KRAN AIR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0321017', 'nama_kom' => 'PAKU', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0321019', 'nama_kom' => 'PASIR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0321020', 'nama_kom' => 'SEMEN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0321021', 'nama_kom' => 'GIPSUM', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0321022', 'nama_kom' => 'BAJA RINGAN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0321026', 'nama_kom' => 'MULTIROOF/GENTENG METAL', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0321027', 'nama_kom' => 'KUSEN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0321028', 'nama_kom' => 'PIPA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0321029', 'nama_kom' => 'SENG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0321093', 'nama_kom' => 'BESI HOLLOW', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0322001', 'nama_kom' => 'TUKANG BUKAN MANDOR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0322002', 'nama_kom' => 'BIAYA KEAMANAN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '033', 'nama_kom' => 'PENYEDIAAN AIR DAN LAYANAN PERUMAHAN LAINNYA', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0331001', 'nama_kom' => 'TARIF AIR MINUM PAM', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0332001', 'nama_kom' => 'IURAN PEMBUANGAN SAMPAH', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0334001', 'nama_kom' => 'IURAN BULANAN RT', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '034', 'nama_kom' => 'LISTRIK DAN BAHAN BAKAR RUMAH TANGGA', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0341001', 'nama_kom' => 'TARIF LISTRIK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0342002', 'nama_kom' => 'BAHAN BAKAR RUMAH TANGGA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '04', 'nama_kom' => 'PERLENGKAPAN, PERALATAN DAN PEMELIHARAAN RUTIN RUMAH TANGGA', 'flag' => 1, 'flag_2' => 0],
                ['kode_kom' => '041', 'nama_kom' => 'FURNITUR, PERLENGKAPAN DAN KARPET', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0411002', 'nama_kom' => 'JAM DINDING', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0411003', 'nama_kom' => 'KARPET', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0411004', 'nama_kom' => 'KASUR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0411005', 'nama_kom' => 'KURSI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0411006', 'nama_kom' => 'LEMARI PAKAIAN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0411009', 'nama_kom' => 'MEJA KURSI TAMU', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0411012', 'nama_kom' => 'RAK PIRING', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0411016', 'nama_kom' => 'SOFA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0411017', 'nama_kom' => 'SPRING BED', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '042', 'nama_kom' => 'TEKSTIL RUMAH TANGGA', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0421001', 'nama_kom' => 'BANTAL', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0421002', 'nama_kom' => 'KAIN GORDEN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0421003', 'nama_kom' => 'SELIMUT', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0421004', 'nama_kom' => 'SPREY', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0421006', 'nama_kom' => 'HANDUK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '043', 'nama_kom' => 'PERALATAN RUMAH TANGGA', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0431001', 'nama_kom' => 'KULKAS/LEMARI ES', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0431002', 'nama_kom' => 'DISPENSER', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0431003', 'nama_kom' => 'KOMPOR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0431015', 'nama_kom' => 'MESIN CUCI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0431017', 'nama_kom' => 'AIR CONDITIONER (AC)', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0431021', 'nama_kom' => 'PEMANAS AIR(WATER HEATER)', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0432001', 'nama_kom' => 'BLENDER', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0432003', 'nama_kom' => 'MAGIC COM/MAGIC JAR/ RICE COOKER', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0432019', 'nama_kom' => 'KIPAS ANGIN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0432020', 'nama_kom' => 'SETRIKA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0433001', 'nama_kom' => 'SERVICE AC', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '044', 'nama_kom' => 'BARANG PECAH BELAH DAN PERALATAN MAKAN MINUM', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0441003', 'nama_kom' => 'PIRING', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0441011', 'nama_kom' => 'SENDOK/GARPU', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0441013', 'nama_kom' => 'EMBER', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0441014', 'nama_kom' => 'PANCI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0441015', 'nama_kom' => 'PENGGORENGAN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0441016', 'nama_kom' => 'STOPLES', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0441017', 'nama_kom' => 'TERMOS', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0441019', 'nama_kom' => 'BOTOL MINUMAN PLASTIK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '045', 'nama_kom' => 'PERALATAN DAN PERLENGKAPAN PERUMAHAN DAN KEBUN', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0451001', 'nama_kom' => 'POMPA AIR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0452027', 'nama_kom' => 'ALAT-ALAT LISTRIK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0452028', 'nama_kom' => 'BATU BATERAY', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0452029', 'nama_kom' => 'BOLA LAMPU', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0452032', 'nama_kom' => 'LAMPU LED', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '046', 'nama_kom' => 'BARANG DAN LAYANAN UNTUK PEMELIHARAAN RUMAH TANGGA RUTIN', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0461001', 'nama_kom' => 'KAIN PEL DENGAN TANGKAI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0461002', 'nama_kom' => 'SAPU', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0461003', 'nama_kom' => 'PEMBERSIH LANTAI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0461004', 'nama_kom' => 'PEMUTIH', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0461005', 'nama_kom' => 'PENGHARUM CUCIAN/ PELEMBUT', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0461006', 'nama_kom' => 'PENYEGAR RUANGAN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0461007', 'nama_kom' => 'SABUN CAIR/CUCI PIRING', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0461008', 'nama_kom' => 'SABUN CREAM DETERGEN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0461010', 'nama_kom' => 'SABUN DETERGEN BUBUK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0461011', 'nama_kom' => 'PELICIN/ PEWANGI PAKAIAN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0461030', 'nama_kom' => 'DETERGEN CAIR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0461032', 'nama_kom' => 'PEMBERSIH PORSELEN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0461036', 'nama_kom' => 'KAMPER', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0461037', 'nama_kom' => 'PEMBASMI NYAMUK BAKAR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0461039', 'nama_kom' => 'PEMBASMI NYAMUK SPRAY', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0462001', 'nama_kom' => 'UPAH ASISTEN RUMAH TANGGA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0462002', 'nama_kom' => 'UPAH BABY SITTER', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '05', 'nama_kom' => 'KESEHATAN', 'flag' => 1, 'flag_2' => 0],
                ['kode_kom' => '051', 'nama_kom' => 'OBAT-OBATAN DAN PRODUK KESEHATAN', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0511001', 'nama_kom' => 'OBAT DENGAN RESEP', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0511002', 'nama_kom' => 'PIL KB', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0511003', 'nama_kom' => 'VITAMIN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0511005', 'nama_kom' => 'OBAT BATUK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0511006', 'nama_kom' => 'OBAT SAKIT KEPALA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0511007', 'nama_kom' => 'OBAT FLU', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0511009', 'nama_kom' => 'OBAT PENURUN PANAS', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0511010', 'nama_kom' => 'OBAT MAAG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0511043', 'nama_kom' => 'JAMU', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0511044', 'nama_kom' => 'OBAT GOSOK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0512001', 'nama_kom' => 'ALAT KB LAINNYA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0512038', 'nama_kom' => 'MASKER', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0513001', 'nama_kom' => 'POPOK DEWASA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0513002', 'nama_kom' => 'KACA MATA PLUS DAN MINUS', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '052', 'nama_kom' => 'JASA RAWAT JALAN', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0521001', 'nama_kom' => 'BIAYA UNTUK KB', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0521002', 'nama_kom' => 'TARIF BIDAN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0521003', 'nama_kom' => 'IMUNISASI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0522001', 'nama_kom' => 'TARIF DOKTER GIGI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0523001', 'nama_kom' => 'TARIF DOKTER SPESIALIS', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0523002', 'nama_kom' => 'TARIF DOKTER UMUM', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '053', 'nama_kom' => 'JASA RAWAT INAP', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0531001', 'nama_kom' => 'TARIF RUMAH SAKIT', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '054', 'nama_kom' => 'JASA KESEHATAN LAINNYA', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0541001', 'nama_kom' => 'TARIF CHECK UP', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0541002', 'nama_kom' => 'TARIF LABORATORIUM', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '06', 'nama_kom' => 'TRANSPORTASI', 'flag' => 1, 'flag_2' => 0],
                ['kode_kom' => '061', 'nama_kom' => 'PEMBELIAN KENDARAAN', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0611001', 'nama_kom' => 'MOBIL', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0612001', 'nama_kom' => 'SEPEDA MOTOR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0613001', 'nama_kom' => 'SEPEDA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '062', 'nama_kom' => 'PENGOPERASIAN PERALATAN TRANSPORTASI PRIBADI', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0621001', 'nama_kom' => 'BAN DALAM MOTOR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0621002', 'nama_kom' => 'BAN LUAR MOBIL', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0621003', 'nama_kom' => 'BAN LUAR MOTOR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0621007', 'nama_kom' => 'ACCU', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0621041', 'nama_kom' => 'HELM', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0622001', 'nama_kom' => 'SOLAR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0622002', 'nama_kom' => 'BENSIN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0622004', 'nama_kom' => 'PELUMAS/OLI MESIN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0623001', 'nama_kom' => 'PEMELIHARAAN/SERVICE', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0623002', 'nama_kom' => 'PERBAIKAN RINGAN KENDARAAN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0623004', 'nama_kom' => 'CUCI KENDARAAN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0624001', 'nama_kom' => 'TARIF PARKIR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0624006', 'nama_kom' => 'TARIF JALAN TOL', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0624010', 'nama_kom' => 'BIAYA ADMINISTRASI PENERBITAN SIM', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0624011', 'nama_kom' => 'BIAYA ADMINISTRASI PENERBITAN STNK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0624018', 'nama_kom' => 'KENDARAAN CARTER/RENTAL', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '063', 'nama_kom' => 'JASA ANGKUTAN PENUMPANG', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0631001', 'nama_kom' => 'TARIF KERETA API', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0632001', 'nama_kom' => 'ANGKUTAN ANTAR KOTA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0632002', 'nama_kom' => 'ANGKUTAN DALAM KOTA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0632005', 'nama_kom' => 'TARIF KENDARAAN TRAVEL', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0632006', 'nama_kom' => 'TARIF KENDARAAN RODA 4 ONLINE', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0632008', 'nama_kom' => 'TARIF KENDARAAN RODA 2 ONLINE', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0633001', 'nama_kom' => 'ANGKUTAN UDARA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0634001', 'nama_kom' => 'ANGKUTAN SUNGAI, DANAU DAN PENYEBERANGAN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0634002', 'nama_kom' => 'ANGKUTAN LAUT', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '064', 'nama_kom' => 'JASA PENGIRIMAN BARANG', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0641001', 'nama_kom' => 'BIAYA PENGIRIMAN BARANG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '07', 'nama_kom' => 'INFORMASI, KOMUNIKASI, DAN JASA KEUANGAN', 'flag' => 1, 'flag_2' => 0],
                ['kode_kom' => '071', 'nama_kom' => 'PERALATAN INFORMASI DAN KOMUNIKASI', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0712001', 'nama_kom' => 'TELEPON SELULER', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0713002', 'nama_kom' => 'LAPTOP/NOTEBOOK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0713003', 'nama_kom' => 'KOMPUTER TABLET', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0713005', 'nama_kom' => 'PRINTER', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0714002', 'nama_kom' => 'TELEVISI BERWARNA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0714004', 'nama_kom' => 'SPEAKER', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '072', 'nama_kom' => 'LAYANAN INFORMASI DAN KOMUNIKASI', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0721001', 'nama_kom' => 'TARIF TELEPON', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0722001', 'nama_kom' => 'TARIF PULSA PONSEL', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0723001', 'nama_kom' => 'BIAYA LANGGANAN INTERNET', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0724001', 'nama_kom' => 'BIAYA JARINGAN SALURAN TV', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '073', 'nama_kom' => 'ASURANSI', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0731001', 'nama_kom' => 'BIAYA ADMINISTRASI ASURANSI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '074', 'nama_kom' => 'JASA KEUANGAN', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0741001', 'nama_kom' => 'BIAYA ADMINISTRASI KARTU KREDIT', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0742001', 'nama_kom' => 'BIAYA ADMINISTRASI KARTU ATM', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0742002', 'nama_kom' => 'BIAYA ADMINISTRASI TRANSFER UANG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0742003', 'nama_kom' => 'BIAYA ADMINISTRASI BUKU TABUNGAN BANK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '08', 'nama_kom' => 'REKREASI, OLAHRAGA, DAN BUDAYA', 'flag' => 1, 'flag_2' => 0],
                ['kode_kom' => '081', 'nama_kom' => 'BARANG REKREASI TAHAN LAMA', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0811001', 'nama_kom' => 'KAMERA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '082', 'nama_kom' => 'BARANG REKREASI LAINNYA DAN OLAHRAGA', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0821008', 'nama_kom' => 'MAINAN ANAK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0821009', 'nama_kom' => 'SEPEDA ANAK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0824003', 'nama_kom' => 'MAKANAN HEWAN PELIHARAAN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '083', 'nama_kom' => 'LAYANAN REKREASI DAN OLAHRAGA', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0835002', 'nama_kom' => 'JASA DOKTER HEWAN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0836001', 'nama_kom' => 'REKREASI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0836020', 'nama_kom' => 'FITNES CENTER', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0836021', 'nama_kom' => 'KOLAM RENANG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0836024', 'nama_kom' => 'SEWA LAPANGAN FUTSAL', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '084', 'nama_kom' => 'PERLENGKAPAN KEBUDAYAAN', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0841002', 'nama_kom' => 'GITAR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '085', 'nama_kom' => 'LAYANAN KEBUDAYAAN', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0851001', 'nama_kom' => 'BIOSKOP', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0853001', 'nama_kom' => 'JASA FOTO STUDIO', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0859001', 'nama_kom' => 'KURSUS MUSIK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '086', 'nama_kom' => 'KORAN, BUKU, DAN PERLENGKAPAN SEKOLAH', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0861001', 'nama_kom' => 'BUKU PELAJARAN AKADEMI/UNIVERSITAS', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0861002', 'nama_kom' => 'BUKU PELAJARAN SD', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0861003', 'nama_kom' => 'BUKU PELAJARAN SMP', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0861004', 'nama_kom' => 'BUKU PELAJARAN SMA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0864002', 'nama_kom' => 'BUKU TULIS BERGARIS', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0864005', 'nama_kom' => 'PENSIL HITAM', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0864006', 'nama_kom' => 'PULPEN/BOLLPOINT', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0864007', 'nama_kom' => 'TAS SEKOLAH', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '09', 'nama_kom' => 'PENDIDIKAN', 'flag' => 1, 'flag_2' => 0],
                ['kode_kom' => '091', 'nama_kom' => 'PENDIDIKAN DASAR DAN ANAK USIA DINI', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0911001', 'nama_kom' => 'TAMAN KANAK KANAK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0911002', 'nama_kom' => 'KELOMPOK BERMAIN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0911004', 'nama_kom' => 'SEKOLAH DASAR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '092', 'nama_kom' => 'PENDIDIKAN MENENGAH', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0921001', 'nama_kom' => 'SEKOLAH MENENGAH PERTAMA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0921002', 'nama_kom' => 'SEKOLAH MENENGAH ATAS', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '093', 'nama_kom' => 'PENDIDIKAN TINGGI', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0931001', 'nama_kom' => 'AKADEMI/PERGURUAN TINGGI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '094', 'nama_kom' => 'PENDIDIKAN LAINNYA', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '0941001', 'nama_kom' => 'BIMBINGAN BELAJAR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0941005', 'nama_kom' => 'TAMAN PENDIDIKAN ALQURAN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0941006', 'nama_kom' => 'KURSUS SEMPOA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '0941009', 'nama_kom' => 'KURSUS BAHASA ASING', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '10', 'nama_kom' => 'PENYEDIAAN MAKANAN DAN MINUMAN/RESTORAN ', 'flag' => 1, 'flag_2' => 0],
                ['kode_kom' => '101', 'nama_kom' => 'JASA PELAYANAN MAKANAN DAN MINUMAN', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '1011002', 'nama_kom' => 'PIZZA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011003', 'nama_kom' => 'MIE', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011004', 'nama_kom' => 'STEAK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011006', 'nama_kom' => 'KUE KERING BERMINYAK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011008', 'nama_kom' => 'AYAM BAKAR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011009', 'nama_kom' => 'AYAM GORENG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011011', 'nama_kom' => 'BUBUR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011012', 'nama_kom' => 'BUBUR KACANG HIJAU', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011013', 'nama_kom' => 'CAPCAI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011014', 'nama_kom' => 'PEMPEK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011015', 'nama_kom' => 'GADO-GADO', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011016', 'nama_kom' => 'GUDEG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011017', 'nama_kom' => 'GULAI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011018', 'nama_kom' => 'HAMBURGER', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011019', 'nama_kom' => 'IKAN BAKAR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011020', 'nama_kom' => 'KETUPAT / LONTONG SAYUR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011021', 'nama_kom' => 'MARTABAK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011022', 'nama_kom' => 'NASI DENGAN LAUK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011024', 'nama_kom' => 'PEPES', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011025', 'nama_kom' => 'PECEL', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011027', 'nama_kom' => 'RAWON', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011028', 'nama_kom' => 'RENDANG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011029', 'nama_kom' => 'RUJAK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011030', 'nama_kom' => 'SATE', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011031', 'nama_kom' => 'SIOMAY', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011032', 'nama_kom' => 'SOTO', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011033', 'nama_kom' => 'TONGSENG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011035', 'nama_kom' => 'SOP', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011040', 'nama_kom' => 'TAHU CAMPUR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011042', 'nama_kom' => 'IKAN GORENG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011045', 'nama_kom' => 'MASAKAN JEPANG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011046', 'nama_kom' => 'BEBEK GORENG', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011048', 'nama_kom' => 'FU YUNG HAI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011051', 'nama_kom' => 'SEBLAK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011052', 'nama_kom' => 'BATAGOR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011053', 'nama_kom' => 'ROTI BAKAR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011055', 'nama_kom' => 'ES', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011056', 'nama_kom' => 'KOPI SIAP SAJI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011057', 'nama_kom' => 'TEH SIAP SAJI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011060', 'nama_kom' => 'TAHU TELOR/TAHU TEK-TEK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011062', 'nama_kom' => 'KALDU KACANG HIJAU', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011063', 'nama_kom' => 'BAKSO SIAP SANTAP', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1011090', 'nama_kom' => 'RUJAK CINGUR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '11', 'nama_kom' => 'PERAWATAN PRIBADI DAN JASA LAINNYA', 'flag' => 1, 'flag_2' => 0],
                ['kode_kom' => '111', 'nama_kom' => 'PERAWATAN PRIBADI', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '1112001', 'nama_kom' => 'TISSU', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1112002', 'nama_kom' => 'LOTION ANTI NYAMUK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1112003', 'nama_kom' => 'PEMBALUT WANITA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1112004', 'nama_kom' => 'ALAS BEDAK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1112005', 'nama_kom' => 'BEDAK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1112006', 'nama_kom' => 'HAND BODY LOTION', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1112007', 'nama_kom' => 'KAPAS', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1112008', 'nama_kom' => 'LIPSTIK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1112009', 'nama_kom' => 'MINYAK RAMBUT', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1112010', 'nama_kom' => 'PARFUM', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1112011', 'nama_kom' => 'PELEMBAB WAJAH', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1112012', 'nama_kom' => 'PEMBERSIH/PENYEGAR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1112013', 'nama_kom' => 'PASTA GIGI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1112014', 'nama_kom' => 'SABUN MANDI CAIR', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1112015', 'nama_kom' => 'SABUN MANDI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1112016', 'nama_kom' => 'SABUN WAJAH', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1112017', 'nama_kom' => 'SHAMPO', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1112018', 'nama_kom' => 'SIKAT GIGI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1112019', 'nama_kom' => 'DEODORANT', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1112022', 'nama_kom' => 'PISAU CUKUR/SILET', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1112026', 'nama_kom' => 'KRIM WAJAH', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1112072', 'nama_kom' => 'SERUM KECANTIKAN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1112093', 'nama_kom' => 'HAND SANITIZER', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1113002', 'nama_kom' => 'TARIF GUNTING RAMBUT PRIA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1113003', 'nama_kom' => 'TARIF GUNTING RAMBUT WANITA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1113004', 'nama_kom' => 'TARIF GUNTING RAMBUT ANAK', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1113009', 'nama_kom' => 'CREAMBATH', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1113010', 'nama_kom' => 'FACIAL / PEELING', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1113013', 'nama_kom' => 'PIJAT NON MEDIS/URUT/ REFLEKSI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '112', 'nama_kom' => 'PERAWATAN PRIBADI LAINNYA', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '1121001', 'nama_kom' => 'EMAS PERHIASAN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1121002', 'nama_kom' => 'JAM TANGAN', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1129001', 'nama_kom' => 'KOREK API GAS', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1129002', 'nama_kom' => 'POPOK BAYI SEKALI PAKAI/ DIAPERS', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1129005', 'nama_kom' => 'DOMPET', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1129006', 'nama_kom' => 'KACA MATA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1129008', 'nama_kom' => 'TAS TANGAN WANITA', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1129009', 'nama_kom' => 'KOPER', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1129011', 'nama_kom' => 'TAS', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1129012', 'nama_kom' => 'BEDAK BAYI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1129046', 'nama_kom' => 'SABUN BAYI', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '113', 'nama_kom' => 'PERLINDUNGAN SOSIAL', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '1131001', 'nama_kom' => 'JASA PENITIPAN ANAK/ DAY CARE', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '119', 'nama_kom' => 'JASA LAINNYA', 'flag' => 2, 'flag_2' => 1],
                ['kode_kom' => '1191001', 'nama_kom' => 'BIAYA FOTO COPY', 'flag' => 3, 'flag_2' => 2],
                ['kode_kom' => '1191002', 'nama_kom' => 'BIAYA PRINT', 'flag' => 3, 'flag_2' => 2],
        ]);
    }
}
